version: 0.2

phases:
  install:
    commands:
      - echo installing nodejs...
      - echo done installing...
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      # - echo testing...
      # - echo building...
      - ng build --prod
  post_build:
    commands:
      - mv appspec.yml ./dist/yash-portfolio
      - mv scripts ./dist/yash-portfolio
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/yash-portfolio
